import React, { useState, useEffect } from "react";
import { DashboardLayout } from "../components/DashboardLayout";
import { apiClient } from "../App";
import { toast } from "sonner";
import { 
  Lightbulb, 
  TreePine, 
  AlertTriangle, 
  TrendingUp,
  DollarSign,
  Download,
  Loader2,
  RefreshCw,
  CheckCircle2,
  Shield,
  Target,
  BarChart3
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { Progress } from "../components/ui/progress";
import { Badge } from "../components/ui/badge";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  Radar
} from "recharts";

const COLORS = ['#1A4D2E', '#4F6F52', '#F9E400', '#3B82F6', '#EF4444', '#8B5CF6'];

const InsightsPage = () => {
  const [insights, setInsights] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [downloading, setDownloading] = useState(false);

  useEffect(() => {
    fetchInsights();
  }, []);

  const fetchInsights = async () => {
    try {
      const response = await apiClient.get("/insights/generate");
      setInsights(response.data);
    } catch (error) {
      toast.error("Failed to load insights");
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const regenerateInsights = async () => {
    setGenerating(true);
    try {
      const response = await apiClient.get("/insights/generate");
      setInsights(response.data);
      toast.success("AI insights regenerated!");
    } catch (error) {
      toast.error("Failed to regenerate insights");
    } finally {
      setGenerating(false);
    }
  };

  const downloadReport = async () => {
    setDownloading(true);
    try {
      const response = await apiClient.get("/insights/report");
      const report = response.data;
      
      // Create downloadable report
      const reportContent = `
ECOPULSE SUSTAINABILITY REPORT
==============================
Generated: ${new Date(report.report_date).toLocaleDateString()}
Organization: ${report.organization}
Period: ${report.period.start || 'N/A'} to ${report.period.end || 'N/A'}

EXECUTIVE SUMMARY
-----------------
Total Carbon Footprint: ${report.executive_summary.total_carbon_footprint_kg} kg CO₂
Total Activities Tracked: ${report.executive_summary.total_activities_tracked}
Sustainability Score: ${report.executive_summary.sustainability_score}/100
Trees Equivalent to Offset: ${report.executive_summary.trees_equivalent}
Top Emission Source: ${report.executive_summary.top_emission_source}

EMISSIONS BREAKDOWN
-------------------
Activity Emissions: ${report.emissions_breakdown.activity_emissions} kg CO₂
Energy Emissions: ${report.emissions_breakdown.energy_emissions} kg CO₂

By Category:
${Object.entries(report.emissions_breakdown.by_category || {}).map(([cat, val]) => `  - ${cat}: ${val} kg CO₂`).join('\n')}

By Month:
${Object.entries(report.emissions_breakdown.by_month || {}).map(([month, val]) => `  - ${month}: ${val} kg CO₂`).join('\n')}

GOALS PROGRESS
--------------
Active Goals: ${report.goals_progress.active}
Completed Goals: ${report.goals_progress.completed}
${report.goals_progress.goals.map(g => `  - ${g.title}: ${g.progress.toFixed(0)}% complete`).join('\n')}

RECOMMENDATIONS
---------------
${report.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

---
Report generated by EcoPulse NGO Sustainability Platform
`;
      
      // Download as text file
      const blob = new Blob([reportContent], { type: 'text/plain' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `ecopulse-sustainability-report-${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      
      toast.success("Report downloaded successfully!");
    } catch (error) {
      toast.error("Failed to download report");
    } finally {
      setDownloading(false);
    }
  };

  if (loading) {
    return (
      <DashboardLayout>
        <div className="flex items-center justify-center h-96">
          <Loader2 className="w-8 h-8 animate-spin text-[#1A4D2E]" />
        </div>
      </DashboardLayout>
    );
  }

  const categoryData = insights?.emissions_by_category 
    ? Object.entries(insights.emissions_by_category).map(([name, value]) => ({
        name: name.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
        value: Math.round(value * 100) / 100
      }))
    : [];

  const getRiskColor = (level) => {
    switch (level) {
      case "low": return "bg-green-100 text-green-800 border-green-200";
      case "medium": return "bg-amber-100 text-amber-800 border-amber-200";
      case "high": return "bg-red-100 text-red-800 border-red-200";
      default: return "bg-gray-100 text-gray-800";
    }
  };

  const getRiskIcon = (level) => {
    switch (level) {
      case "low": return <CheckCircle2 className="w-5 h-5 text-green-600" />;
      case "medium": return <AlertTriangle className="w-5 h-5 text-amber-600" />;
      case "high": return <AlertTriangle className="w-5 h-5 text-red-600" />;
      default: return <Shield className="w-5 h-5 text-gray-600" />;
    }
  };

  return (
    <DashboardLayout>
      <div className="space-y-8 animate-fade-in">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div>
            <h1 className="font-heading text-3xl font-bold text-[#1A1A1A]">Sustainability Insights</h1>
            <p className="text-[#71717A] mt-1">AI-powered analysis and recommendations</p>
          </div>
          
          <div className="flex items-center gap-3">
            <Button 
              variant="outline" 
              onClick={regenerateInsights}
              disabled={generating}
              data-testid="regenerate-insights-btn"
            >
              {generating ? (
                <Loader2 className="w-4 h-4 animate-spin mr-2" />
              ) : (
                <RefreshCw className="w-4 h-4 mr-2" />
              )}
              Regenerate
            </Button>
            <Button 
              className="btn-primary"
              onClick={downloadReport}
              disabled={downloading}
              data-testid="download-report-btn"
            >
              {downloading ? (
                <Loader2 className="w-4 h-4 animate-spin mr-2" />
              ) : (
                <Download className="w-4 h-4 mr-2" />
              )}
              Download Report
            </Button>
          </div>
        </div>

        {/* Key Metrics Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {/* Trees Saved */}
          <Card className="card-base overflow-hidden" data-testid="trees-saved-card">
            <div className="absolute top-0 right-0 w-32 h-32 -mr-8 -mt-8 opacity-10">
              <TreePine className="w-full h-full text-[#22C55E]" />
            </div>
            <CardContent className="p-6 relative">
              <div className="flex items-start justify-between">
                <div>
                  <p className="text-sm text-[#71717A] mb-1">Trees Equivalent</p>
                  <p className="font-heading text-4xl font-bold text-[#22C55E]">
                    {insights?.trees_saved_equivalent?.toLocaleString() || 0}
                  </p>
                  <p className="text-sm text-[#71717A] mt-1">to offset emissions</p>
                </div>
                <div className="w-14 h-14 rounded-2xl bg-[#22C55E]/10 flex items-center justify-center">
                  <TreePine className="w-7 h-7 text-[#22C55E]" />
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Sustainability Score */}
          <Card className="card-base" data-testid="sustainability-score-card">
            <CardContent className="p-6">
              <div className="flex items-start justify-between mb-4">
                <div>
                  <p className="text-sm text-[#71717A] mb-1">Sustainability Score</p>
                  <p className="font-heading text-4xl font-bold text-[#1A4D2E]">
                    {insights?.sustainability_score || 50}
                  </p>
                  <p className="text-sm text-[#71717A] mt-1">out of 100</p>
                </div>
                <div className="w-14 h-14 rounded-2xl bg-[#1A4D2E]/10 flex items-center justify-center">
                  <Target className="w-7 h-7 text-[#1A4D2E]" />
                </div>
              </div>
              <Progress 
                value={insights?.sustainability_score || 50} 
                className="h-3 bg-[#F5F7F5]"
              />
            </CardContent>
          </Card>

          {/* Risk Monitor */}
          <Card className="card-base" data-testid="risk-monitor-card">
            <CardContent className="p-6">
              <div className="flex items-start justify-between">
                <div>
                  <p className="text-sm text-[#71717A] mb-1">Risk Level</p>
                  <Badge className={`text-lg px-3 py-1 ${getRiskColor(insights?.risk_assessment?.level)}`}>
                    {(insights?.risk_assessment?.level || 'low').toUpperCase()}
                  </Badge>
                  <p className="text-sm text-[#71717A] mt-2">
                    {insights?.risk_assessment?.factors?.length || 0} factors identified
                  </p>
                </div>
                <div className="w-14 h-14 rounded-2xl bg-amber-50 flex items-center justify-center">
                  {getRiskIcon(insights?.risk_assessment?.level)}
                </div>
              </div>
            </CardContent>
          </Card>

          {/* ROI */}
          <Card className="card-base" data-testid="roi-card">
            <CardContent className="p-6">
              <div className="flex items-start justify-between">
                <div>
                  <p className="text-sm text-[#71717A] mb-1">Cost per kg CO₂</p>
                  <p className="font-heading text-4xl font-bold text-[#1A1A1A]">
                    ${insights?.roi_metrics?.cost_per_kg_co2?.toFixed(2) || '0.00'}
                  </p>
                  <p className="text-sm text-[#22C55E] mt-1">
                    {insights?.roi_metrics?.potential_savings_percent || 0}% potential savings
                  </p>
                </div>
                <div className="w-14 h-14 rounded-2xl bg-[#F9E400]/20 flex items-center justify-center">
                  <DollarSign className="w-7 h-7 text-[#D9C600]" />
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Charts Row */}
        <div className="grid lg:grid-cols-2 gap-6">
          {/* Emissions by Category */}
          <Card className="card-base" data-testid="emissions-pie-chart">
            <CardHeader>
              <CardTitle className="font-heading text-lg">Emissions by Category</CardTitle>
            </CardHeader>
            <CardContent>
              {categoryData.length > 0 ? (
                <ResponsiveContainer width="100%" height={300}>
                  <PieChart>
                    <Pie
                      data={categoryData}
                      cx="50%"
                      cy="50%"
                      innerRadius={60}
                      outerRadius={100}
                      paddingAngle={2}
                      dataKey="value"
                      label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                      labelLine={false}
                    >
                      {categoryData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip 
                      formatter={(value) => [`${value} kg CO₂`, 'Emissions']}
                      contentStyle={{ 
                        backgroundColor: '#fff', 
                        border: '1px solid #E5E7EB',
                        borderRadius: '8px'
                      }}
                    />
                  </PieChart>
                </ResponsiveContainer>
              ) : (
                <div className="h-300 flex items-center justify-center text-[#71717A]">
                  <p>No emission data available yet</p>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Category Bar Chart */}
          <Card className="card-base" data-testid="emissions-bar-chart">
            <CardHeader>
              <CardTitle className="font-heading text-lg">Category Comparison</CardTitle>
            </CardHeader>
            <CardContent>
              {categoryData.length > 0 ? (
                <ResponsiveContainer width="100%" height={300}>
                  <BarChart data={categoryData} layout="vertical">
                    <CartesianGrid strokeDasharray="3 3" stroke="#E5E7EB" />
                    <XAxis type="number" tick={{ fill: '#71717A', fontSize: 12 }} />
                    <YAxis 
                      type="category" 
                      dataKey="name" 
                      width={100}
                      tick={{ fill: '#71717A', fontSize: 11 }}
                    />
                    <Tooltip 
                      formatter={(value) => [`${value} kg CO₂`, 'Emissions']}
                      contentStyle={{ 
                        backgroundColor: '#fff', 
                        border: '1px solid #E5E7EB',
                        borderRadius: '8px'
                      }}
                    />
                    <Bar dataKey="value" fill="#1A4D2E" radius={[0, 4, 4, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              ) : (
                <div className="h-300 flex items-center justify-center text-[#71717A]">
                  <p>Track activities to see comparisons</p>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Risk Factors */}
        {insights?.risk_assessment?.factors?.length > 0 && (
          <Card className="card-base" data-testid="risk-factors-card">
            <CardHeader>
              <CardTitle className="font-heading text-lg flex items-center gap-2">
                <AlertTriangle className="w-5 h-5 text-amber-500" />
                Risk Factors
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {insights.risk_assessment.factors.map((factor, index) => (
                  <div 
                    key={index}
                    className="flex items-center gap-3 p-3 rounded-lg bg-amber-50 border border-amber-100"
                  >
                    <AlertTriangle className="w-5 h-5 text-amber-500 flex-shrink-0" />
                    <span className="text-[#4A4A4A]">{factor}</span>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}

        {/* AI Recommendations */}
        <Card className="card-base bg-gradient-to-br from-[#1A4D2E] to-[#4F6F52]" data-testid="ai-recommendations-card">
          <CardHeader>
            <CardTitle className="font-heading text-lg text-white flex items-center gap-2">
              <Lightbulb className="w-5 h-5 text-[#F9E400]" />
              AI-Powered Recommendations
            </CardTitle>
            <p className="text-white/70 text-sm">
              Based on your consumption patterns and activity data, GPT-5.2 analyzed and provided personalized suggestions
            </p>
          </CardHeader>
          <CardContent>
            {insights?.recommendations?.length > 0 ? (
              <div className="space-y-3">
                {insights.recommendations.map((rec, index) => (
                  <div 
                    key={index}
                    className="flex items-start gap-3 p-4 rounded-xl bg-white/10 backdrop-blur-sm border border-white/10 hover:bg-white/15 transition-colors"
                    data-testid={`recommendation-${index}`}
                  >
                    <div className="w-8 h-8 rounded-full bg-[#F9E400] flex items-center justify-center flex-shrink-0">
                      <span className="font-bold text-[#1A1A1A] text-sm">{index + 1}</span>
                    </div>
                    <p className="text-white/90 leading-relaxed">{rec}</p>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-center py-8 text-white/70">
                <Lightbulb className="w-12 h-12 mx-auto mb-4 opacity-50" />
                <p>Track more activities to get AI-powered recommendations</p>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Data Summary */}
        <Card className="card-base" data-testid="data-summary-card">
          <CardHeader>
            <CardTitle className="font-heading text-lg flex items-center gap-2">
              <BarChart3 className="w-5 h-5 text-[#1A4D2E]" />
              Data Summary
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-6">
              <div className="text-center p-4 rounded-xl bg-[#F5F7F5]">
                <p className="font-heading text-3xl font-bold text-[#1A1A1A]">
                  {insights?.data_summary?.total_activities || 0}
                </p>
                <p className="text-sm text-[#71717A]">Total Activities</p>
              </div>
              <div className="text-center p-4 rounded-xl bg-[#F5F7F5]">
                <p className="font-heading text-3xl font-bold text-[#1A1A1A]">
                  {insights?.data_summary?.energy_data_points || 0}
                </p>
                <p className="text-sm text-[#71717A]">Energy Records</p>
              </div>
              <div className="text-center p-4 rounded-xl bg-[#F5F7F5]">
                <p className="font-heading text-3xl font-bold text-[#1A4D2E]">
                  {insights?.data_summary?.active_goals || 0}
                </p>
                <p className="text-sm text-[#71717A]">Active Goals</p>
              </div>
              <div className="text-center p-4 rounded-xl bg-[#F5F7F5]">
                <p className="font-heading text-3xl font-bold text-[#22C55E]">
                  {insights?.data_summary?.completed_goals || 0}
                </p>
                <p className="text-sm text-[#71717A]">Completed Goals</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Total Emissions Summary */}
        <Card className="card-base card-highlight" data-testid="emissions-summary-card">
          <CardContent className="p-6">
            <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
              <div>
                <p className="text-sm text-[#71717A]">Total Carbon Footprint</p>
                <p className="font-heading text-4xl font-bold text-[#1A1A1A]">
                  {insights?.total_emissions_kg?.toLocaleString() || 0} kg CO₂
                </p>
                <p className="text-sm text-[#71717A] mt-1">
                  Activities: {insights?.activity_emissions_kg?.toLocaleString() || 0} kg | 
                  Energy: {insights?.energy_emissions_kg?.toLocaleString() || 0} kg
                </p>
              </div>
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-2xl bg-[#1A4D2E]/10 flex items-center justify-center">
                  <TrendingUp className="w-6 h-6 text-[#1A4D2E]" />
                </div>
                <div className="text-right">
                  <p className="text-sm text-[#71717A]">Total Cost Tracked</p>
                  <p className="font-heading text-xl font-bold text-[#1A1A1A]">
                    ${insights?.roi_metrics?.total_cost_tracked?.toLocaleString() || '0.00'}
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
};

export default InsightsPage;
